fn main() {
    println!("this how a function fails");
    std::process::exit(1);
}
